version: '2'

services:
  reviews:
    build: './'
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
    restart: unless-stopped

  database:
    build: 'database/'
    environment: 
      MYSQL_ROOT_PASSWORD: root
    tty: true
